/**
 * BOSE SIGNALS
 * Fine-grained reactivity for resumable frameworks.
 */

export class Signal {
  constructor(value, id) {
    this._value = value;
    this.id = id;
    this.subscribers = new Set();
  }

  get value() {
    // If we're in a "Tracking" phase, add the current subscriber
    if (context.activeSubscriber) {
      this.subscribers.add(context.activeSubscriber);
    }
    return this._value;
  }

  set value(newValue) {
    if (this._value === newValue) return;
    this._value = newValue;
    this.notify();
  }

  notify() {
    this.subscribers.forEach(sub => sub.update(this._value));
    
    // Global notification for resumable synchronization
    if (typeof window !== 'undefined' && window.__BOSE_SYNC__) {
        window.__BOSE_SYNC__(this.id, this._value);
    }
  }

  toJSON() {
    return this._value;
  }
}

const context = {
  activeSubscriber: null
};

export function useSignal(initialValue, id) {
  // In a real framework, 'id' is generated by the compiler
  return new Signal(initialValue, id);
}
